### ISSUE TITLE
New codegeneration annotations

### ISSUE THREAD

**Issue by y9vad9** [y9vad9/implier#1]
I think it will be necessary to create something like `@DSLImpl` and simple java-styled builder `@BuilderImpl` codegenerations.

**Comment by y9vad9** [comment]
also maybe it would be good if we have factory-function generation to hide mutable / immutable realization where type clarifying is not necessary. I mean next:
```kotlin
@FactoryFunctionImpl
@ImmutableImpl
interface Foo {
   val value: String
}
```
will generate next:
```kotlin
fun Foo(value: String): Foo = ImmutableFoo(value)
```

**Comment by y9san9** [comment]
Nice ideas, especially with DSLs, I'm really interested in. So can you propose how the DSLs generation may look like?

The cases I want to be covered:
- simple dsl generation
- DSL generation with check support (e.g.: if username less than 5 symbols → throw an exception)
- DSL finalization:
    ```kotlin
        class DSLScope {
            var variable: String = "" // do not forget to pass the default value
            var variable2: Int = 0  // do not forget to pass the default value
            
            fun state(): DSLScopeState = DSLScopeState(variable, variable2)
        }
        class DSLScopeState(val variable: String, val variable2: Int)
    ```

**Comment by y9san9** [comment]
The most complex thing here is how to design validators.
I see three ways:
- (Not convenient for me, but still the way) design it with notations and annotations:
    ```kotlin
    // object here is notation, we assuming that user will
    // create object here, but not class. Anyway this will
    // be checked at compile time
    object NameValidator : Validator<String> {
        override fun validate(value: String): Boolean = ...
    }

    @Validate(NameValidator::class)
    val name: String = ""
    ```
- (Not convenient for me, but still the way) design it with function name notations:
    ```kotlin
    var name: String = ...
    fun _checkName_(): Boolean = ...
    ```
    Transformed to → 
    ```kotlin
    private var _name: String
    var name: String get() = _name set() = if(/* code from _checkName_() */) ... else ...
    ```
- (Now I'm looking forward this) Wrap it with a type:
    ```kotlin
    val name: Validate<String> = Validate(default = ...) { name -> require(name.length in 1..30) { "Provide a correct name" } }
    ```
    Transformed to →
    ```kotlin
    var _name: String = default
    var name get() = _name set() = if(/* code from name.validate() */) ... else ...
    ```

**Comment by y9vad9** [comment]
Thanks for your suggestions.
I don't see any legal variant to transform types via `ksp` at compile-time, so I suggest next variant:
```kotlin
@ImmutableImpl
interface Foo {
   val value: String
   
   @Validator(propertyName = "value")
   val validator: Validator<String> get() = StringLengthValidator(1..99) 
}
```
I don't see any variants for wrapping concretely `value` (with saving interface implementation for mutable & immutable realizations)

**Comment by y9vad9** [comment]
I moved data validation discussion to a new issue #2
