### ISSUE TITLE
Generate mutable interface?

### ISSUE THREAD

**Issue by manosbatsis** [y9vad9/implier#11]
As you can see in https://github.com/y9vad9/implier/pull/10 I've added marker interfaces like `Mutable<T>` to allow slightly generic use of the generated APIs but in practice it would be far more useful if 

```kotlin
@ImmutableImpl
@MutableImpl
interface Sample {
    val sample: String
    val number: Int
}
```

generated: 

```kotlin
interface MutableSample: Sample {
    override var sample: String
    override var number: Int
}

class ImmutableSampleImpl(
  public override val sample: String,
  public override val number: Int
) : Sample

class MutableSampleImpl(
  public override var sample: String,
  public override var number: Int
) : MutableSample
```

Would happily update my PR to include this one.

**Comment by y9vad9** [comment]
Is there any need in superfluous interface? There was such generation before, but I've removed it becase there wasn't any case or reason to do so.
